name: Deploy API Dyzulk (FTP)

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ğŸ‰ Build & Deploy
    runs-on: ubuntu-latest
    steps:
      # 1. Ambil Kode
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4


      # 3. Siapkan Node.js & Build React/Inertia
      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: ğŸ”¨ Build Frontend Assets
        run: |
          npm ci
          npm run build
          # Hapus node_modules agar proses upload cepat
          rm -rf node_modules 

      # Buat file trigger untuk Cron Job cPanel
      - name: ğŸ“ Create Deploy Trigger
        run: touch .deploy_trigger

      # 4. Kirim File ke cPanel via FTP
      - name: ğŸ“‚ Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Path FTP tujuan, karena akun FTP API sudah mengarah ke /home/dyzulkc2/public_domain/api.dyzulk.com/
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/tests/**
            **/storage/*.key
            .env
            vendor/**
